# vim: ft=dockerfile
FROM centos:latest

RUN yum groupinstall 'Development Tools' -y
RUN yum install cmake clang-libs clang-devel clang -y
RUN curl -sSf https://sh.rustup.rs | sh -s -- -y
RUN bash -c ". $HOME/.cargo/env && cargo install bindgen"
